name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11.0
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: 0.8.677
    - name: Build uberjar
      run: ./bin/build
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: transcribble-1.0.0-SNAPSHOT-standalone.jar
        path: target
